# Tutorial Python
## Introdução Numpy
* https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html
* https://medium.com/programadores-ajudando-programadores/brincando-com-numpy-parte-1-vetores-vs-listas-51f4867ea0f1
* https://www.geeksforgeeks.org/python-lists-vs-numpy-arrays/

In [ ]:
import numpy as np

In [ ]:
# cria uma matriz unidimensional
mt = np.array([12,34,26,18,10])
print(mt)
print(type(mt))

# flexibilidade de operações matemáticas
mt2 = mt * 2
print(mt2)

[12 34 26 18 10]
<class 'numpy.ndarray'>
[24 68 52 36 20]


In [ ]:
lst = [10,20,30]
print(lst)
lst = lst*5
print(lst)

[10, 20, 30]
[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]


In [ ]:
# Numpy array a partir de uma lista
lst = [1,2,3,4,5,6]
arr = np.array(lst)
print(lst)
print(arr)
print(type(arr))

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# Cria um vetor sequencial
mt = np.arange(1,15)
print(mt)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [ ]:
#mudar o tipo do array
# Podemos transformar tipos de dados de arrays
mtnew = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])
print(mtnew)
# quando transformamos de float para int os valores são truncados
mtnewint = mtnew.astype(np.int64)
print(mtnewint)

[ 1.4       3.6      -5.1       9.42      4.999999]
[ 1  3 -5  9  4]


In [ ]:
# podemos fazer o inverso também.
mt5 = np.array([1, 2, 3, 4])
print(mt5)
mt6 = mt5.astype(float)
print(mt6)

[1 2 3 4]
[1. 2. 3. 4.]


In [ ]:
# mais de uma dimensão
# cria um matriz bidimensional
mt7 = np.array([[7,2,23],[12,27,4],[5,34,23]])
print(mt7)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]


In [ ]:
#valores aleatórios entre zero e um
rnd = np.random.random((6))
print(rnd)
print("-------")
#valores aleatórios distr. normal contendo negativos
rnd2= np.random.randn((5))
print(rnd2)
print("-------")
# Valores inteiros aleatórios (3x5)
rnd3 = np.random.randint(100, size=(3, 5))
print(rnd3)

[[0.60337343 0.3641359  0.65097095]
 [0.09702018 0.99544544 0.70381223]]
-------
[-0.13478156  1.15598738  2.41897141 -0.15450579 -0.66685042]
-------
[[ 8 24 21 64  9]
 [66 59  6 41 86]
 [37 28 47 67 67]]


In [ ]:
#outra forma de gerar aleatórios
#uso de semente
gnr = np.random.default_rng(11)
rnd = gnr.random(13)
print (rnd)

#gerar inteiros
rnd = gnr.integers(10, size=(1, 12))
print(rnd)

[0.1285702  0.49927786 0.60149836 0.02868901 0.14792608 0.92821102
 0.07042058 0.12977395 0.94832845 0.62188359 0.36899312 0.51139002
 0.66284295]
[[9 2 8 1 3 7 2 6 4 5 9 8]]


In [ ]:
#unique remove repetições
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [ ]:
#funções específicas
# cria a matriz bidimensional k
k = np.array([[17,22,43],[27,25,14],[15,24,32],[151,241,321]])
# Mostra a matriz k
print(k)
# Mostra um elemento específico da matriz k
print(k[0][2])
# Mostra o tamanho das dimensões da matriz k
print(k.shape)

[[ 17  22  43]
 [ 27  25  14]
 [ 15  24  32]
 [151 241 321]]
43
(4, 3)


In [ ]:
#Funções Matemáticas
# Mostra o maior valor da matriz k
print(np.max(k))
# Mostra o menor valor da matriz k
print(np.min(k))
# Mostra a soma dos valores da matriz k
print((np.sum(k)))
# Mostra o valor da média dos valores da matriz k
print(np.mean(k))
# Mostra o valor do desvio padrão (standard deviation) dos valores da matiz k
print(np.std(k))
# Mostra o valor damediana dos valores da matiz k
print(np.median(k))

321
14
932
77.66666666666667
98.96744694875964
26.0


In [ ]:
#extração de elementos
m = np.array([1, 2, 3, 4, 5, 6])
# Mostra o elemento da posição 2
print(m[1])
print("-------")
# Mostra o array criado a partir da posição 0, dois elementos
print(m[0:2])
print("-------")
# Mostra o array criado a partir da 2a posição
# até todo o restante do array
print(m[1:])
print("-------")
# Mostra o array criado a partir da antepenúltima
#posição até o final
print(m[-3:])

2
-------
[1 2]
-------
[2 3 4 5 6]
-------
[4 5 6]


In [ ]:
# Redimensiona Matriz
rnd = np.arange(15).reshape((5, 3))
print(rnd)
print("-------")
# mostra a matriz com 5 linhas e 3 colunas
new_rnd = np.reshape(rnd, (3,5))
print(new_rnd)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
-------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [ ]:
# Cria um novo array com inserções no final
# Array original não é alterado
arr = np.array([[0,2,4],[6,8,10]])
new_arr = np.append(arr, [13,15,17])
print(new_arr)

[ 0  2  4  6  8 10 13 15 17]


In [ ]:
print(arr)

[[ 0  2  4]
 [ 6  8 10]]


In [ ]:
new_arr = np.reshape(new_arr, (3,3))
new_arr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [13, 15, 17]])

In [ ]:
#expressões lógicas
#usando where
# criando matriz com valores aleatórios positivos e negativos
v = np.random.randn(4, 4)
print(v)
# criando matriz com valores booleanos baseado no array v
x = (v > 0)
print(x)
# substitui os valores negativos por 1
v[v<0] = 1
print(v)


[[-0.50376347 -0.18097024  0.84732791  1.99951174]
 [-0.22736984  0.72741771  0.70945385 -0.80437231]
 [-0.62894141  0.29400003 -0.82525965 -1.32020175]
 [-0.22979492  2.09244556  0.77428095 -0.45996153]]
[[False False  True  True]
 [False  True  True False]
 [False  True False False]
 [False  True  True False]]
[[1.         1.         0.84732791 1.99951174]
 [1.         0.72741771 0.70945385 1.        ]
 [1.         0.29400003 1.         1.        ]
 [1.         2.09244556 0.77428095 1.        ]]
